{% set provider = "Ignition" %}
{% set goname = "github.com/terraform-providers/terraform-provider-"+provider.lower() %}
{% set version = "1.1.0" %}

{% set name = goname.split('/')[-1] %}

{% set x4_plugin = name + '_v' + version + "_x4" %}

{% set sha256 = "14998d0321ef093435d00d840487dc3ef3b9866b162f04216cda14d9a9d1608c" %}
{% set sha256_win64 = "95b1e76e775995608712137cafe04ad50af469cad71c0ba01b1e78114fa46160" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://{{ goname }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}


build:
  number: 0
  script:
    - go build -v -o {{ target_gobin }}{{ x4_plugin }}{{ target_goexe }}

requirements:
  build:
    - {{ compiler('go') }} 1.13
  run:
    - terraform 0.12

test:
  commands:
    # Create a sample init.tf loading the provider
    - echo 'provider "{{ provider|lower }}" { version="{{ version }}" }' > init.tf  # [unix]
    - echo provider "{{ provider|lower }}" { version="{{ version }}" } > init.tf    # [win]

    # Initialize
    - terraform init

    # Tests that init was successful
    - test -f .terraform/plugins/{{ target_goos }}_{{ target_goarch }}/lock.json              # [unix]
    - if not exist .terraform\plugins\{{ target_goos }}_{{ target_goarch }}\lock.json exit 1  # [win]

    # Test that the provider was not downloaded
    - test ! -f .terraform/plugins/{{ target_goos }}_{{ target_goarch }}/{{ x4_plugin }}{{ target_goexe }}        # [unix]
    - if exist .terraform\plugins\{{ target_goos }}_{{ target_goarch }}\{{ x4_plugin }}{{ target_goexe }} exit 1  # [win]

about:
  home: https://www.terraform.io
  license: MPL-2.0
  summary: The Terraform {{ provider }} provider
  doc_url: https://www.terraform.io/docs/providers/{{ provider|lower }}/index.html
  dev_url: https://github.com/terraform-providers/{{ name }}

extra:
  recipe-maintainers:
    - conda-forge/terraform
