appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: yQjLwYef36fOjfvhs3vpddRlAWwtVonSpMv8zOAdMZeUqmpgbiRy0G/+bngM7kf2BeCeblW/G8cy9354TDQnUsTVSRnZng9xea7mhr/DfASsy+vE8xxrgw9+N31Olp7cwq3Xg4vXJyJNA3uXx8azFNj9NMPAx+9Q5gs7SY+WO+GKEPGSCBdfWqqoYhQ3V8sgiefRtiMLiWI8axLFEU9vUeny1zidT9Irt3yH5Ar+AsnD8N027rjsSx6HDfyRdmHmSqQLeRr/ndtQ6NQNiuxO2TQc/0rILuVAgW7hTAlbB7OilnRLkfDee3ptjTBNdjb2pHh/58onlRB95E3vTY2GOAvvCZ73/fKdYsyfaq8hiXYMgjeTvrEtKUGPy8LeuiwB/FCHaHAgIxSFawMskfc/7zI8f/t1y2XaOXYX2J1srr2ReBohW1HCqps7+KgFKSLQk7CfNOWE7KLelTin3tlaW39QdOHVpWpsqZ9dQmIYYOPNuKS3q6snFw6GRIyqwj7wJNfcYYB7fD5yu/0Jd6Yz8ttpE83NC4WMskFNaBUYF0ATlkl/V7Ed3TNi8akaWbPq6xFnn7F2tANjRuboSjRXokBpcGB/YbzdXrjidjAOMPnlw3GV3oISFGT2ZgLZHp5kaH+IC9JMx7RP/vgPwSRF+H+FIHbIdkoqTS7ibkqD4O4=}
provider:
  win: azure
bot:
  automerge: true
